<a href="https://colab.research.google.com/github/hjmohamedbilal/movies-dataset/blob/main/MohamedBilalHJProgram2Lab2Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Titanic Dataset: Data Exploration and Cleaning with Pandas

1. Import the required library

In [1]:
import pandas as pd

2. Load the dataset

In [2]:
file_path = "Titanic-3CS03.csv"
df = pd.read_csv(file_path)
print("Dataset loaded successfully.")
print("Number of rows: {df.shape[0]}")
print("Number of columns: {df.shape[1]}")

Dataset loaded successfully.
Number of rows: {df.shape[0]}
Number of columns: {df.shape[1]}

3. Inspect the data

3.1 Display the full dataset

In [3]:
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
30,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
31,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
32,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
33,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
34,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
35,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
36,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
37,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
38,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
39,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
40,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
41,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

3.2 View the first and last rows

In [4]:
display(df.head())
display(df.tail())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
37,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
38,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
39,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
40,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
41,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

3.3 View column names

In [5]:
print("Column names:")
print(df.columns.tolist())

Column names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

3.4 Check dataset dimensions

In [6]:
rows, columns = df.shape
print(f"Rows: {rows}")
print(f"Columns: {columns}")

Rows: 42
Columns: 12

3.5 Check data types

In [7]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

3.6 Get a compact structural summary

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  42 non-null     int64
 1   Survived     42 non-null     int64
 2   Pclass       42 non-null     int64
 3   Name         42 non-null     object
 4   Sex          42 non-null     object
 5   Age          35 non-null     float64
 6   SibSp        42 non-null     int64
 7   Parch        42 non-null     int64
 8   Ticket       42 non-null     object
 9   Fare         42 non-null     float64
 10  Cabin        13 non-null     object
 11  Embarked     42 non-null     object
dtypes: float64(2), int64(5), object(5)
memory usage: 4.1+ KB

3.7 Summary statistics

In [9]:
display(df.describe())

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,42.000000,42.000000,42.000000,35.000000,42.000000,42.000000,42.000000
mean,12.928571,0.523810,2.380952,27.657143,0.690476,0.523810,28.058031
std,8.674023,0.505487,0.854040,16.406496,1.047368,1.173656,41.092143
min,1.000000,0.000000,1.000000,2.000000,0.000000,0.000000,7.225000
25%,6.000000,0.000000,2.000000,14.500000,0.000000,0.000000,8.050000
50%,11.000000,1.000000,3.000000,27.000000,0.000000,0.000000,16.700000
75%,19.750000,1.000000,3.000000,36.500000,1.000000,0.750000,30.070800
max,30.000000,1.000000,3.000000,58.000000,4.000000,5.000000,263.000000

4. Identify missing values

4.1 Display missing-value locations

In [10]:
display(df.isna())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,True,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,False,False,False,True,False
15,False,False,False,False,False,False,False,False,False,False,True,False
16,False,False,False,False,False,False,False,False,False,False,True,False
17,False,False,False,False,False,True,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,True,False
19,False,False,False,False,False,True,False,False,False,False,True,False
20,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,True,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,True,False
25,False,False,False,False,False,False,False,False,False,False,True,False
26,False,False,False,False,False,True,False,False,False,False,True,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,True,False,False,False,False,True,False
29,False,False,False,False,False,True,False,False,False,False,True,False
30,False,False,False,False,False,False,False,False,False,False,True,False
31,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,True,False
33,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,True,False
35,False,False,False,False,False,True,False,False,False,False,True,False
36,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,True,False
38,False,False,False,False,False,False,False,False,False,False,True,False
39,False,False,False,False,False,False,False,False,False,False,True,False
40,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False

4.2 Count missing values in each column

In [11]:
missing_before = df.isna().sum().sort_values(ascending=False)
print("Missing values in each column:")
display(missing_before.to_frame(name="Missing count"))

Missing values in each column:

             Missing count
Cabin                   29
Age                      7
PassengerId              0
Survived                 0
Name                     0
Pclass                   0
SibSp                    0
Sex                      0
Parch                    0
Ticket                   0
Fare                     0
Embarked                 0

5. Handle missing values

In [13]:
# Fill missing Age values using the median age.
if "Age" in df.columns:
  age_median = df["Age"].median()
  df["Age"] = df["Age"].fillna(age_median)
  print(f"Missing Age values filled with median: {age_median}")
# Fill missing Fare values using the mean fare.
if "Fare" in df.columns:
  fare_mean = df["Fare"].mean()
  df["Fare"] =df["Fare"].fillna(fare_mean)
  print(f"Missing Fare values filled with mean: {fare_mean}")
# Fill missing Embarked values using the most frequent category.
if "Embarked" in df.columns:
  embarked_mode = df["Embarked"].mode(dropna=True)
  if not embarked_mode.empty:
    df["Embarked"] = df["Embarked"].fillna(embarked_mode.iloc[0])
    print(f"Missing Embarked values filled with mode: {embarked_mode.iloc[0]}")
    display(df.head())

Missing Age values filled with median: 27.0
Missing Fare values filled with mean: 28.05803095238095
Missing Embarked values filled with mode: S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

5.1 Check missing values again

In [14]:
missing_after_imputation = df.isna().sum().sort_values(ascending=False)
display(missing_after_imputation.to_frame(name="Missing count"))

             Missing count
Cabin                   29
PassengerId              0
Pclass                   0
Survived                 0
Name                     0
Sex                      0
SibSp                    0
Age                      0
Parch                    0
Ticket                   0
Fare                     0
Embarked                 0

6. Find and remove duplicate rows

In [15]:
duplicate_count = df.duplicated().sum()
print(f"Exact duplicate rows found: {duplicate_count}")
df = df.drop_duplicates().copy()
print(f"Rows remaining after duplicate removal: {len(df)}")

Exact duplicate rows found: 12
Rows remaining after duplicate removal: 30

7. Decide how to handle any remaining missing values

In [16]:
print("Rows before optional complete-case filtering:", len(df))
df_complete = df.dropna().copy()
print("Rows if all rows with any missing value were removed:", len(df_complete))
print("Rows that would be removed:", len(df) - len(df_complete))
# We continue with df (not df_complete) so that we do not silently discard rows.

Rows before optional complete-case filtering: 30
Rows if all rows with any missing value were removed: 8
Rows that would be removed: 22

8. Convert categorical columns into numeric columns

In [17]:
categorical_columns = [col for col in ["Sex", "Embarked"] if col in df.columns]
if categorical_columns:
  df = pd.get_dummies(
      df,
      columns=categorical_columns,
      dtype=int
  )
  print("Encoded categorical columns:", categorical_columns)
else:
  print("No requested categorical columns were found; nothing to encode.")
  display(df.head())

Encoded categorical columns: ['Sex', 'Embarked']

9. Validate the cleaned dataset

In [18]:
print("cleaned dataset preview:")
display(df.head())
print("\nFinal shape (rows, columns):", df.shape)
print("\nMissing values by column:")
display(df.isna().sum().to_frame(name="Missing count"))
print("\nExact duplicate rows remaining:", df.duplicated().sum())

cleaned dataset preview:

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,0,1,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,1,0,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,0,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,1,0,0,0,1
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,0,1,0,0,1

Final shape (rows, columns): (30, 15)

Missing values by column:

             Missing count
PassengerId              0
Survived                 0
Pclass                   0
Name                     0
Age                      0
SibSp                    0
Parch                    0
Ticket                   0
Fare                     0
Cabin                   22
Sex_female               0
Sex_male                 0
Embarked_C               0
Embarked_Q               0
Embarked_S               0

Exact duplicate rows remaining: 0

10. Save the cleaned dataset

In [19]:
output_path = "titanic_3CS03-Cleaned.csv"
df.to_csv(output_path, index=False)
print(f"Data cleaning completed. Cleaned file saved as: {output_path}")

Data cleaning completed. Cleaned file saved as: titanic_3CS03-Cleaned.csv