<a href="https://colab.research.google.com/github/hjmohamedbilal/movies-dataset/blob/main/MohamedBilalHJExperiment4BTDS332.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment 3: Combining and Analysing Student Data with Pandas

1. Import Pandas and load the two CSV files

In [1]:
import pandas as pd
# Load student details and marks from two separate CSV files.
df_info = pd.read_csv("student_info.csv")
df_marks = pd.read_csv("student_marks.csv")
print("Student information dataset:")
display(df_info)
print("\nStudent marks dataset:")
display(df_marks)

Student information dataset:

,StudentID,Name,Age,Gender,Class,City,Phone,Email,Guardian,AdmissionYear
0,S001,Aarav Sharma,17,Male,12A,Bengaluru,9876500001,aarav.sharma@example.com,Ramesh Sharma,2022
1,S002,Diya Patel,16,Female,11B,Mumbai,9876500002,diya.patel@example.com,Kiran Patel,2023
2,S003,Kabir Singh,17,Male,12A,Delhi,9876500003,kabir.singh@example.com,Harpreet Singh,2022
3,S004,Ananya Rao,16,Female,11A,Chennai,9876500004,ananya.rao@example.com,Suresh Rao,2023
4,S005,Vivaan Gupta,18,Male,12B,Hyderabad,9876500005,vivaan.gupta@example.com,Anil Gupta,2021
5,S006,Ishita Nair,17,Female,12A,Kochi,9876500006,ishita.nair@example.com,Manoj Nair,2022
6,S007,Aditya Verma,16,Male,11B,Pune,9876500007,aditya.verma@example.com,Rajesh Verma,2023
7,S008,Saanvi Iyer,17,Female,12B,Coimbatore,9876500008,saanvi.iyer@example.com,Karthik Iyer,2022
8,S009,Reyansh Joshi,18,Male,12A,Ahmedabad,9876500009,reyansh.joshi@example.com,Deepak Joshi,2021
9,S010,Myra Kulkarni,16,Female,11A,Nagpur,9876500010,myra.kulkarni@example.com,Prakash Kulkarni,2023

Student marks dataset:

,StudentID,Name,Subject1,Subject2,Subject3,Subject4,Subject5,TotalMarks,Percentage,Grade
0,S003,Kabir Singh,88,76,92,81,79,416,83.2,A
1,S004,Ananya Rao,95,89,91,93,90,458,91.6,A+
2,S005,Vivaan Gupta,60,55,70,65,58,308,61.6,C
3,S006,Ishita Nair,78,82,75,80,77,392,78.4,B+
4,S007,Aditya Verma,45,50,55,48,52,250,50.0,D
5,S008,Saanvi Iyer,90,85,88,92,87,442,88.4,A
6,S009,Reyansh Joshi,70,68,72,65,69,344,68.8,B
7,S010,Myra Kulkarni,84,80,86,83,81,414,82.8,A
8,S011,Kavya Menon,73,77,70,75,72,367,73.4,B
9,S012,Arjun Malhotra,55,60,58,62,59,294,58.8,C

In [2]:
# Inspect the size and column names of each dataset.
print("Student information shape (rows, columns):", df_info.shape)
print("Student marks shape (rows, columns):", df_marks.shape)
print("\nColumns in student information:", df_info.columns.tolist())
print("Columns in student marks:", df_marks.columns.tolist())
# Check whether the joining key is present in both datasets.
assert "StudentID" in df_info.columns, "StudentID is missing from student_info.csv"
assert "StudentID" in df_marks.columns, "StudentID is missing from student_marks.csv"

Student information shape (rows, columns): (10, 10)
Student marks shape (rows, columns): (10, 10)

Columns in student information: ['StudentID', 'Name', 'Age', 'Gender', 'Class', 'City', 'Phone', 'Email', 'Guardian', 'AdmissionYear']
Columns in student marks: ['StudentID', 'Name', 'Subject1', 'Subject2', 'Subject3', 'Subject4', 'Subject5', 'TotalMarks', 'Percentage', 'Grade']

2. Understand the four types of joins

2.1 Inner join - only matching students

In [3]:
inner_join = pd.merge(
    df_info,
    df_marks,
    on="StudentID",
    how="inner",
    suffixes=("_info", "_marks")
)
print("Inner join shape (rows, columns):", inner_join.shape)
display(inner_join[["StudentID", "Name_info", "Class", "Name_marks", "Percentage", "Grade"]])

Inner join shape (rows, columns): (8, 19)

  StudentID      Name_info Class     Name_marks  Percentage Grade
0      S003    Kabir Singh   12A    Kabir Singh        83.2     A
1      S004     Ananya Rao   11A     Ananya Rao        91.6    A+
2      S005   Vivaan Gupta   12B   Vivaan Gupta        61.6     C
3      S006    Ishita Nair   12A    Ishita Nair        78.4    B+
4      S007   Aditya Verma   11B   Aditya Verma        50.0     D
5      S008    Saanvi Iyer   12B    Saanvi Iyer        88.4     A
6      S009  Reyansh Joshi   12A  Reyansh Joshi        68.8     B
7      S010  Myra Kulkarni   11A  Myra Kulkarni        82.8     A

2.2 Outer join - all students from both datasets

In [4]:
outer_join = pd.merge(
    df_info,
    df_marks,
    on="StudentID",
    how="outer",
    suffixes=("_info", "_marks")
)
print("Outer join shape (rows, columns):", outer_join.shape)
display(outer_join[["StudentID", "Name_info", "Class", "Name_marks", "Percentage", "Grade"]])

Outer join shape (rows, columns): (12, 19)

   StudentID      Name_info Class      Name_marks  Percentage Grade
0       S001   Aarav Sharma   12A             NaN         NaN   NaN
1       S002     Diya Patel   11B             NaN         NaN   NaN
2       S003    Kabir Singh   12A     Kabir Singh        83.2     A
3       S004     Ananya Rao   11A      Ananya Rao        91.6    A+
4       S005   Vivaan Gupta   12B    Vivaan Gupta        61.6     C
5       S006    Ishita Nair   12A     Ishita Nair        78.4    B+
6       S007   Aditya Verma   11B    Aditya Verma        50.0     D
7       S008    Saanvi Iyer   12B     Saanvi Iyer        88.4     A
8       S009  Reyansh Joshi   12A   Reyansh Joshi        68.8     B
9       S010  Myra Kulkarni   11A   Myra Kulkarni        82.8     A
10      S011            NaN   NaN     Kavya Menon        73.4     B
11      S012            NaN   NaN  Arjun Malhotra        58.8     C

2.3 Left join - keep all records from student information

In [6]:
left_join = pd.merge(
    df_info,
    df_marks,
    on="StudentID",
    how="left",
    suffixes=("_info", "_marks")
)
print("Left join shape (rows, columns):", left_join.shape)
display(left_join[["StudentID", "Name_info", "Class", "Name_marks", "Percentage", "Grade"]])

Left join shape (rows, columns): (10, 19)

  StudentID      Name_info Class     Name_marks  Percentage Grade
0      S001   Aarav Sharma   12A            NaN         NaN   NaN
1      S002     Diya Patel   11B            NaN         NaN   NaN
2      S003    Kabir Singh   12A    Kabir Singh        83.2     A
3      S004     Ananya Rao   11A     Ananya Rao        91.6    A+
4      S005   Vivaan Gupta   12B   Vivaan Gupta        61.6     C
5      S006    Ishita Nair   12A    Ishita Nair        78.4    B+
6      S007   Aditya Verma   11B   Aditya Verma        50.0     D
7      S008    Saanvi Iyer   12B    Saanvi Iyer        88.4     A
8      S009  Reyansh Joshi   12A  Reyansh Joshi        68.8     B
9      S010  Myra Kulkarni   11A  Myra Kulkarni        82.8     A

2.4 Right join - keep all records from student marks

In [7]:
right_join = pd.merge(
    df_info,
    df_marks,
    on="StudentID",
    how="right",
    suffixes=("_info", "_marks")
)
print("Right join shape (rows, columns):", right_join.shape)
display(right_join[["StudentID", "Name_info", "Class", "Name_marks", "Percentage", "Grade"]])

Right join shape (rows, columns): (10, 19)

  StudentID      Name_info Class      Name_marks  Percentage Grade
0      S003    Kabir Singh   12A     Kabir Singh        83.2     A
1      S004     Ananya Rao   11A      Ananya Rao        91.6    A+
2      S005   Vivaan Gupta   12B    Vivaan Gupta        61.6     C
3      S006    Ishita Nair   12A     Ishita Nair        78.4    B+
4      S007   Aditya Verma   11B    Aditya Verma        50.0     D
5      S008    Saanvi Iyer   12B     Saanvi Iyer        88.4     A
6      S009  Reyansh Joshi   12A   Reyansh Joshi        68.8     B
7      S010  Myra Kulkarni   11A   Myra Kulkarni        82.8     A
8      S011            NaN   NaN     Kavya Menon        73.4     B
9      S012            NaN   NaN  Arjun Malhotra        58.8     C

3. Inspect missing values in the outer-joined dataset

In [8]:
merged = outer_join.copy()
print("Missing values in each column:")
display(merged.isna().sum().to_frame(name="Missing value count"))
print("\nRecords with a missing student name or percentage:")
display(merged[merged[["Name_info", "Percentage"]].isna().any(axis=1)])

Missing values in each column:

               Missing value count
StudentID                        0
Name_info                        2
Age                              2
Gender                           2
Class                            2
City                             2
Phone                            2
Email                            2
Guardian                         2
AdmissionYear                    2
Name_marks                       2
Subject1                         2
Subject2                         2
Subject3                         2
Subject4                         2
Subject5                         2
TotalMarks                       2
Percentage                       2
Grade                            2

Records with a missing student name or percentage:

,StudentID,Name_info,Age,Gender,Class,City,Phone,Email,Guardian,AdmissionYear,Name_marks,Subject1,Subject2,Subject3,Subject4,Subject5,TotalMarks,Percentage,Grade
0,S001,Aarav Sharma,17.0,Male,12A,Bengaluru,9.876500e+09,aarav.sharma@example.com,Ramesh Sharma,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,S002,Diya Patel,16.0,Female,11B,Mumbai,9.876500e+09,diya.patel@example.com,Kiran Patel,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,S011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kavya Menon,73.0,77.0,70.0,75.0,72.0,367.0,73.4,B
11,S012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arjun Malhotra,55.0,60.0,58.0,62.0,59.0,294.0,58.8,C

4. Calculate class-wise percentage statistics

In [9]:
grouped = merged.groupby("Class")["Percentage"].agg(
    Mean_Percentage="mean",
    Max_Percentage="max",
    Std_Percentage="std"
).round(2)
print("Class-wise summary of student percentages:")
display(grouped)

Class-wise summary of student percentages:

       Mean_Percentage  Max_Percentage  Std_Percentage
Class
11A               87.2            91.6            6.22
11B               50.0            50.0             NaN
12A               76.8            83.2            7.33
12B               75.0            88.4           18.95

In [10]:
# Optional diagnostic: count valid percentages and records in each class.
class_counts = merged.groupby("Class").agg(
    Total_Records=("StudentID", "size"),
    Valid_Percentage_Count=("Percentage", "count")
)
print("Records and available percentages by class:")
display(class_counts)

Records and available percentages by class:

       Total_Records  Valid_Percentage_Count
Class
11A                2                       2
11B                2                       1
12A                4                       3
12B                2                       2

5. Save the results as CSV files

In [11]:
inner_join.to_csv("inner_join.csv", index=False)
outer_join.to_csv("outer_join.csv", index=False)
left_join.to_csv("left_join.csv", index=False)
right_join.to_csv("right_join.csv", index=False)
grouped.to_csv("grouped_result.csv", index=True)
print("Saved files:")
print("- inner_join.csv")
print("- outer_join.csv")
print("- left_join.csv")
print("- right_join.csv")
print("- grouped_result.csv")

Saved files:
- inner_join.csv
- outer_join.csv
- left_join.csv
- right_join.csv
- grouped_result.csv